
logging:
  level:
    root: info

spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:motel
    username: sa
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
